# Generated by Django 4.1.7 on 2023-04-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('produto', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
